# Build configuration
CXX      := g++
CXXFLAGS := -std=c++17 -Iinclude -Wall -Wextra -MMD -MP

# Directories
SRC_DIR   := src
BUILD_DIR := build

# Final executable
TARGET := oop_project.exe

# Each class is compiled separately into its own object file.
SRCS := main.cpp \
        $(SRC_DIR)/Task.cpp \
        $(SRC_DIR)/Project.cpp \
        $(SRC_DIR)/SchoolProject.cpp \
        $(SRC_DIR)/Manager.cpp

# Mirror the source layout under build/ (e.g. src/Task.cpp -> build/src/Task.o).
OBJS := $(patsubst %.cpp,$(BUILD_DIR)/%.o,$(SRCS))
DEPS := $(OBJS:.o=.d)

.PHONY: all run clean

all: $(TARGET)

# Link all the separately compiled object files into the executable.
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) $^ -o $@

# Compile one class at a time; create the build subdirectory as needed.
$(BUILD_DIR)/%.o: %.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

run: $(TARGET)
	./$(TARGET)

clean:
	rm -rf $(BUILD_DIR) $(TARGET)

# Pull in header dependencies generated by -MMD so edits to a header
# rebuild only the classes that include it.
-include $(DEPS)
